os:
  - linux
  - osx
language: csharp
solution: BeatDetection.sln
install: git clone -q --branch=develop https://github.com/opcon/Substructio ../Substructio
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never