version: 0.11.{build}-appveyor
image: Visual Studio 2015
environment:
  BUTLER_API_KEY:
    secure: 1YditInrUO36VFxX37IzVWUC16FEwJ238DsqhKpgMxuRzyTCR8MTFMbEs6LiNY1f
configuration:
- Debug
- Release
build:
  parallel: true
  verbosity: minimal
build_script:
  - cmd: .\build.cmd mode=%CONFIGURATION%
after_build:
  - cmd: .\build.cmd PushArtifactsAndItchBuilds mode=%CONFIGURATION%
